var regex = /https:\/\/\w+\.safelinks\.protection\.outlook\.com\/\?url=(\S+)\&amp;data[^\s\"']*/g;

function safelinkDecoder (str) {
    return str.replace(regex, (safelinkUri, encodedUri) => decodeURIComponent(encodedUri));
}

// Clean all links in <a> tags
var links = document.body.getElementsByTagName("a");
Array.prototype.forEach.call(
    links,
    link => {
        let href = link.getAttribute("href");
        let originalSrc = link.getAttribute("originalsrc");

        if (originalSrc != null) {
            // First case: the <a> tag was mingled by safelink directly
            link.setAttribute("href", originalSrc);
            link.setAttribute("safelinkhref", href);
        } else if (href.search(regex) > -1) {
            // Second case: the link is raw in the mail, it was generated by Thunderbird
            let decodedUri = safelinkDecoder(href);
            link.setAttribute("safelinkhref", href);
            link.setAttribute("href", decodedUri);
            link.textContent = safelinkDecoder(link.textContent);
        }
});