let outlook_regex = new RegExp('/https://\w+\.safelinks\.protection\.outlook\.com/\?url=(\S+)\&amp;data[^\s"\']*', "g");
let proofpoint_regex = new RegExp('https://urldefense(?:\.proofpoint)?\.com/(v[0-9])/');

function safelinkDecoder (str) {
    return str.replace(outlook_regex, (safelinkUri, encodedUri) => decodeURIComponent(encodedUri));
}

function proofPointDecoder (a) {
    var proofpoint = a.match(proofpoint_regex);
    if (!proofpoint)
        return a;

    var v = proofpoint[1];
    var outurl = a;
    if (v == 'v1') {
        let v1_pattern = new RegExp('https://urldefense(?:\.proofpoint)?\.com/v1/url\\?u=([^&]*)&k=.*');
        outurl = decodeURIComponent(a.match(v1_pattern)[1]);
    } else if (v == 'v2') {
        let v2_pattern = new RegExp('https://urldefense(?:\.proofpoint)?\.com/v2/url\\?u=([^&]*)&[dc]=.*');
        let url = a.match(v2_pattern)[1].replace(/-/g, '%').replace(/_/g, '/');
        outurl = decodeURIComponent(url);
    } else if (v == 'v3') {
        let v3_pattern = new RegExp('https://urldefense(?:\.proofpoint)?\.com/v3/__(.+)__;([^\!]*).*');
        let v3_token_pattern = new RegExp('\\*(\\*.)?', 'g');
        let length_codes = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
        let url = a.match(v3_pattern);
        let encbytes = atob(url[2].replace(/_/g, '/').replace(/-/g, '+'));
        let encbytes_off = 0;

        outurl = url[1].replace(v3_token_pattern, (chunk) => {
            var len = 1;
            if (chunk.length > 1)
               len = length_codes.search(chunk[2]) + 2;
            var out = encbytes.substring(encbytes_off, encbytes_off + len);
            encbytes_off += len;
            return out;
        });
    }

    return outurl;
}

// Clean all links in <a> tags
var links = document.body.getElementsByTagName("a");
Array.prototype.forEach.call(
    links,
    link => {
        let href = link.getAttribute("href");
        if (!href)
            return;
        let originalSrc = link.getAttribute("originalsrc");

        // Decode what Outlook did
        if (originalSrc != null) {
            // First case: the <a> tag was mingled by safelink directly
            link.setAttribute("href", originalSrc);
            link.setAttribute("safelinkhref", href);
            link.setAttribute("title", "Decoded from: " + href);
        } else if (href.search(outlook_regex) > -1) {
            // Second case: the link is raw in the mail, it was generated by Thunderbird
            let decodedUri = safelinkDecoder(href);
            link.setAttribute("safelinkhref", href);
            link.setAttribute("href", decodedUri);
            link.setAttribute("title", "Decoded from: " + href);
            link.textContent = safelinkDecoder(link.textContent);
        }

        // Decode what ProofPoint did -- usually Outlook is the outer one
        // if there are both, since ProofPoint runs on an intermediate
        // mail relay.
        let pphref = link.getAttribute("href");
        if (pphref.search(proofpoint_regex) > -1) {
            let decodedUri = proofPointDecoder(pphref);
            link.setAttribute("urldefensehref", pphref);
            link.setAttribute("href", decodedUri);
            link.setAttribute("title", "Decoded from: " + href);
            link.textContent = proofPointDecoder(link.textContent);
        }
});
